config/routes.rb
Rails.application.routes.draw do
	root "pages#home", as: :home
	get "/about" => "pages#about", as: :about
	resources :signups
	get "/signups/new" => "signups#new", as: :sign
	get "/thanks" => "pages#thanks"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/signup.rb
class Signup < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home

	end
	def about

	end
	def thanks

	end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
	def new
		@signup = Signup.new
	end
	def create
    @signup = Signup.new(signup_params) 
  		if @signup.save 
    		redirect_to '/thanks' 
  		else 
    		render 'new' 
  		end 
  end
	private
	def signup_params
		params.require(:signup).permit(:email, :firstname)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stories</title>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="menu">
		<ul>
			<li><%= link_to "Home", home_path() %></li>
			<li><%= link_to "About", about_path() %></li>
			<li><%= link_to "Contact", sign_path() %></li>
		</ul>
  		<img class="icon-close" src="https://s3.amazonaws.com/codecademy-content/projects/z2d/stories/close-white.svg">
	</div>
	
	<%= yield %>
  	
	<div class="footer">
	  <div class="container">
	    <p>A SHUTTERBUGG PROJECT</p>
	  </div>
	</div>

<script   src="https://code.jquery.com/jquery-3.1.0.min.js"   integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s="   crossorigin="anonymous"></script>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/pages/about.html.erb
<div class="about-main">
	<img id="button" class="icon-menu" src="https://s3.amazonaws.com/codecademy-content/projects/z2d/stories/menu-black.svg">
	<div class="content container">
		<h1>Relive your favorite memories</h1>
	</div>
</div>
<div class="about-supporting">
	<div class="container">
		<h2>No more sorting through photos</h2>
		<p>Stories automatically finds your best photos and creates a new travelogue. This way you can capture and share your special moments in fresh new ways.</p>
		<p>
			<a href="/signups/new" class="btn btn-primary">Sign up</a>
		</p>
	</div>
</div>

app/views/pages/home.html.erb
<div class="home-main">
  <img id="button" class="icon-menu" src="https://s3.amazonaws.com/codecademy-content/projects/z2d/stories/menu-black.svg">
  <div class="container">
    <div class="row">
      <div class="content col-md-6 col-md-offset-6">
      	<h1>Create and share Stories</h1>
        <p>
          <%= link_to "Learn more", about_path(), :class => "btn btn-primary" %>
        </p>
      </div>
    </div>
  </div>
</div>
<div class="home-supporting">
  <div class="container">
    <h2>Relive and share your adventures</h2>
    <p>Stories automatically creates a digital journal filled with only your best photos.</p>
  </div>
</div>
<div class="home-secondary">
  <div class="container">
    
  </div>
</div>
<div class="home-about">
  <div class="container">
    <h2>Discover Stories</h2>
    <p>
      <%= link_to "Learn more", about_path(), :class => "btn btn-primary"%>
    </p>
  </div>
</div>

app/views/pages/thanks.html.erb
<div class="contact-main">
	<img id="button" class="icon-menu" src="https://s3.amazonaws.com/codecademy-content/projects/z2d/stories/menu-black.svg">
	<div class="content container">
		<h1>Thanks. We'll be in touch.</h1>
	</div>
</div>

app/views/signups/new.html.erb
<div class="contact-main">
	<img id="button" class="icon-menu" src="https://s3.amazonaws.com/codecademy-content/projects/z2d/stories/menu-black.svg">
	<div class="content container">
		<h1>Get the latest updates from Stories</h1>
		<div class="row">
			<div class="col-md-4 col-md-4-offset"></div>
			<div class="col-md-4">
				<%= form_for(@signup) do |f| %>
      			<div class="form-group"> 
	            <%= f.label "first name"  %><br> 
	            <%= f.text_field :firstname, class:"form-control" %> 
          	</div>
          	<div class="form-group"> 
	            <%= f.label "Email"  %><br> 
	            <%= f.text_field :email, class:"form-control" %> 
          	</div>
          	<%= f.submit "Join", class:'btn btn-default' %>  
        <% end %>
			</div>
		</div>
	</div>
</div>